### ISSUE TITLE
feat: albumchatcomment 수정

### ISSUE THREAD

**Issue by BiteSnail** [DAILAB-SUZY/PITCH#124]
# 할 일
- [x] API 추가 `GET /api/album/{spotifyAlbumId}/comment/{albumChatCommentId}` 
- [x] musicprofile activity에서albumchat을 가져올 때 parentId가 Null인 것만 가져오도록 로직 수정

**Comment by junhoprog** [comment]
수정 완료했고 확인 부탁드립니다.
