### ISSUE TITLE
Hotfix: FavoriteArtist DTO 설정

### ISSUE THREAD

**Issue by BiteSnail** [DAILAB-SUZY/PITCH#92]
# FavoriteArtistRequest DTO 수정

https://github.com/DAILAB-SUZY/PITCH/blob/6cc96c1b27de19b2c0172ae79201e70152946e72/backend/src/main/java/org/cosmic/backend/domain/favoriteArtist/dtos/FavoriteRequest.java#L13-L23

POST 요청 시 SpotifyId를 받기 때문에 Long에서 String으로 변경해야 함

# FavoriteArtistDetail DTO 수정 

https://github.com/DAILAB-SUZY/PITCH/blob/6cc96c1b27de19b2c0172ae79201e70152946e72/backend/src/main/java/org/cosmic/backend/domain/favoriteArtist/dtos/FavoriteArtistDetail.java#L13-L21

spotifyId가 포함되도록 수정해 주어야 함

# 추가사항
* spotify에서 사용되는 ID인 경우 접두사에 spotify를 붙여야 함
* `/api/favoriteArtist` 에서의 비즈니스 로직도 변경해야 함

**Comment by junhoprog** [comment]
해결 완료했습니다.
