### ISSUE TITLE
Feat : AlbumChatHome API 추가

### ISSUE THREAD

**Issue by ljs831** [DAILAB-SUZY/PITCH#99]
<img width="385" alt="스크린샷 2024-10-23 오후 2 06 28" src="https://github.com/user-attachments/assets/e9a4dd23-9f1e-49aa-be5b-7a03630f7e8f">

API 2개 필요
1. Most Commented API
- 가장 Comment가 많은 **AlbumChat 정보** 가져오기

2. Most LIked API
- 무한 스크롤 형식
- 가장 Album like가 많은 순서대로 **AlbumChat 정보** 가져오기

**Comment by BiteSnail** [comment]
`/albumchat/{albumId}` API에서 AlbumChat 불러오는 API에서 `Long` 을 SpotifyId로 변경

https://github.com/DAILAB-SUZY/PITCH/blob/a9ad5734e1120bde561ceb51a92290a5aa041019/backend/src/main/java/org/cosmic/backend/domain/albumChat/apis/AlbumChatApi.java#L50-L58

**Comment by junhoprog** [comment]
https://github.com/DAILAB-SUZY/PITCH/blob/3695c1c7f5cb7ba8a8ae6bedd429a5a00d1aaddb/backend/src/main/java/org/cosmic/backend/domain/playList/repositorys/AlbumRepository.java#L28-L37
댓글 많은 순, 좋아요 많은 순으로 가져오기 완료
